version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform plan
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform apply --auto-approve
